Updated deployment script.

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -45,25 +45,28 @@ echo "Beginning PHPUnit testing."
 PHPUNIT_OUTPUT=$(bin/phpunit -c app)
 PHPUNIT_STATUS=$?
 
-if [[ $PHPUNIT_STATUS -eq 0 ]]
+echo "$PHPUNIT_OUTPUT"
+
+if [[ $PHPUNIT_STATUS -le 0 ]]
 then
-    echo "$PHPUNIT_OUTPUT"
-    if [[ $PHPUNIT_OUTPUT =~ FAILURES ]]
-    then
-        echo "PHPUnit testing failed.  Please review the output and try again"
-    else
-        echo "No PHPUnit failures detected.  Pushing to origin branch $GIT_BRANCH"
-        git push origin $GIT_BRANCH
-        ORIGIN_PUSH_STATUS=$?
-        if [[ $ORIGIN_PUSH_STATUS -eq 0 ]]
-        then
-            echo "Push to origin branch $GIT_BRANCH successful.  Deploying to Elastic Beanstalk."
-            git aws.push
-        else
-            echo "Unable to push to origin branch $GIT_BRANCH:"
-            exit
-        fi
-    fi
-else
     echo "Unable to initialize PHPUnit.  Make sure that 'bin/phpunit -c app' works."
+    exit
+fi
+
+if [[ $PHPUNIT_OUTPUT =~ FAILURES ]]
+then
+    echo "PHPUnit testing failed.  Please review the output and try again"
+    exit
+fi
+
+echo "No PHPUnit failures detected.  Pushing to origin branch $GIT_BRANCH"
+git push origin $GIT_BRANCH
+ORIGIN_PUSH_STATUS=$?
+if [[ $ORIGIN_PUSH_STATUS -eq 0 ]]
+then
+    echo "Push to origin branch $GIT_BRANCH successful.  Deploying to Elastic Beanstalk."
+    git aws.push
+else
+    echo "Unable to push to origin branch $GIT_BRANCH:"
+    exit
 fi
