Basic entity unit tests complete.

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,9 +1,7 @@
 #! /bin/bash
 
-DEPLOYMENT_ENV = $1
-
 composer update
-COMPOSER_STATUS = $?
+COMPOSER_STATUS=$?
 
 if [[ $COMPOSER_STATUS -eq 1 ]]
 then
@@ -13,23 +11,23 @@ fi
 
 if [[ $COMPOSER_STATUS -eq 1 ]]
 then
-    echo "Unable to update vendors. Make sure 'composer update' or 'php composer.phar update' works."
+   echo "Unable to update vendors. Make sure 'composer update' or 'php composer.phar update' works."
     exit
 fi
 
-PHPUNIT_OUTPUT = $(bin/phpunit -c app)
-PHPUNIT_STATUS = $?
+PHPUNIT_OUTPUT=$(bin/phpunit -c app)
+PHPUNIT_STATUS=$?
 
-if [[ PHPUNIT_STATUS -eq 0 ]]
+if [[ $PHPUNIT_STATUS -eq 0 ]]
 then
-    if [[ $RESULT =~ FAILURES ]]
+    echo "$PHPUNIT_OUTPUT"
+    if [[ $PHPUNIT_OUTPUT =~ FAILURES ]]
     then
         echo "PHPUnit testing failed.  Please review the output and try again"
     else
         echo "No PHPUnit failures detected.  Deploying to Elastic Beanstalk."
-        git aws.push --environment $DEPLOYMENT_ENV
+        git aws.push
     fi
 else
     echo "Unable to initialize PHPUnit."
-    exit
 fi
